### ISSUE TITLE
ERROR: No matching distribution found for tkinter|webbrowser|ttkthemes

### ISSUE THREAD

**Issue by ninetyn1ne** [Arijit-Bhowmick/0x41-MUSIC-PLAYER#2]
While running the setup.py file. I get the following error:-

`ERROR: Could not find a version that satisfies the requirement tkinter|webbrowser|ttkthemes`
`ERROR: No matching distribution found for tkinter|webbrowser|ttkthemes`

I get the same error when setup.py tries to install webbrowser and ttkthemes.
I think the root cause lies in the requirements.txt file which tries to install the module with the name `tkinter` instead of `Tk`. I'd to change `tkinter` with `tk` in the requirements file to avoid such an error.

As for webbrowser, since it is already a part of the [standard python library](https://docs.python.org/3/library/webbrowser.html), I guess we should remove that module from the requirements file. 

Finally, the module `ttkthemes` is not specified in the requirements.txt file so we get an error there too. We need to add this module in the requirements.txt file.

After making all the changes suggested above, the final requirements file should look something like this - 
```
tinytag
pygame==1.9.6
mutagen
Pillow
tk
ttkthemes
```
*Cheers!*
*ninetynine*

**Comment by Arijit-Bhowmick** [comment]
Tkinter and webbrowser are inbuilt python packages in windows, but in case of any linux system it is not available at an immediate stage when the python software is installed in it. 

We have to later install Tkinter module with sudo permission in linux system.

Apart from it, ttkthemes module has not been used in this project.

The requirements.txt file has been modified now.

Thankyou, for your concern about this project.

The issue has been resolved successfully.
